version: '3.7'
services: 

    app:
        build: 
            context: ./app
            target: production
        environment: 
            NODE_ENV: production
            PORT: 4000
        image: app:prod-latest
        ports: 
            - "4000:4000"