version: '3.7'
services: 

    app:
        build: 
            context: ./app
            target: development
        environment: 
            NODE_ENV: development
            PORT: 4000
        image: app:latest
        volumes: 
            - ./app:/home/node/app
        ports: 
            - "4000:4000"